### PR TITLE
Remove default viewer and setup gs-core for ui projects

### PR DESCRIPTION
**Pull request by hichbra**
According the discussion with @pigne, here is a pull request that removes a default UI from gs-core. 

We remove a Swing and JavaFX occurrences and replace them by generics methods. Thus, a adding listener like `void addMouseMotionListener(MouseMotionListener l);` in interface View became `<T, U> void addListener(T descriptor, U listener)`.

The different user interfaces are now in independent projects depending on the technologies used (we have currently two project, [gs-ui-swing](https://github.com/graphstream/gs-ui-swing) and [gs-ui-javafx](https://github.com/graphstream/gs-ui-javafx)). The link between gs-core and all UI projects are done with [Display](https://github.com/hichbra/gs-core/blob/uiScalaToJava/src/org/graphstream/util/Display.java) interface. An implementation of this interface must be defined in UI, it's the entry point of the default display method in Graph.

If this default method is used, you need to select the renderer in the UI project using a system property as before : `System.setProperty("org.graphstream.ui", "org.graphstream.ui.swing.util.Display")` or `System.setProperty("org.graphstream.ui", "org.graphstream.ui.javafx.util.Display")`. For the moment, the pattern used for defined the property is : 
"org.graphstream.ui.\<technology\>.util.\<class implements Display\>"
You can have many display classes in the same package (for example, LegacyDisplay in gs-ui-swing is the old default interface).

### CODE REVIEW

**Comment by gtimbo** [comment]
This is great @hichbra! I have been thinking that it would be really helpful to re-implement the scala viewer in plain Java as I just couldn't see what benefit scala was really providing. I've been making a few changes and fixing a few bugs that are in both the old swing code and the scala code, and am assuming will be in your changes above. The only possible complication is that I've branched off from the original 1.3 release as I couldn't get the 2.0 branch to work properly.

My only real issue with the new UI stuff is that it resides in separate repositories. To me this just makes it more difficult to keep everything in sync and raise issues/enhancements that affect multiple implementations. I'm wondering if putting all UI-related code into a single repository would ultimately be better.

**Comment by hichbra** [comment]
Thanks for your feedback. We saw your pull request in gs-core, but we haven't had time to test it yet. If there is no issue we will include your work do not worry, your changes are on the Style.java so this should not be a problem.
Regarding separate repositories, each directory is an implementation with a different technology, even if the pattern is the same, the code is different. Group them together seems difficult.
But you are absolutely right, it's also difficult to keep everything in sync and debug. This is why there will probably be only one UI really maintained. The rest will be left to the community.

**Comment by gtimbo** [comment]
I've actually made a number of other changes that fix larger bugs, but I haven't created pull requests for them as 1) I've branched immediately after the 1.3 release, as the code got a bit messy and unreliable after that release, and I needed things to work immediately, and 2) they may not work in all situations as I've fixed just enough to get it working in my use-case (although I dare say most of them are relatively complete).

What I would like to do is just create tickets for each of them so that they're known, but that's where I've hit the problem of where to raise those tickets: gs-core? gs-ui? (and now the other two repos)? Maybe I just need to raise the same ticket in each repository.

I understand that each repo uses a different technology, but a single repo can still easily maintain separation (e.g. the base directory structure could be ui-swing/, ui-javafx/, etc).

**Comment by hichbra** [comment]
In case you know the graphic bug location in the code then look at the package, if the class is in org.graphstream.ui..
- geom
- graphicGraph
- layout
- spriteManager
- view
create a ticket in gs-core. These packages contains generics classes used by all UIs. After this pull request, these are the only ones that will stay in gs-core.
If it's not in these packages, that means it's an implementation problem, so do it in the techno repo.

And if you don't know the location, just create a ticket in the repo corresponding to the techno used.

**Comment by gtimbo** [comment]
Technically I know where the tickets should be raised, but my issue is that most of the bugs I've found relate to all of the implementations (well, they've occurred in both the basic Swing renderer and the Scala renderer, as a lot of the code is was essentially copied), which meant raising multiple tickets, which I guess just feels strange to me. Obviously it's a bit different now that the basic renderer doesn't exist any more, and I haven't looked through the JavaFX code to see if the same bugs exist.

By the way, I assume that once this change occurs, you guys will deprecate the gs-ui repository?

**Comment by hichbra** [comment]
BasicRenderer still exists in gs-ui-swing and the new FullRenderer is just a rewriting of the Scala Renderer in Java. So the bugs you have detected are probably still there. gs-ui-javafx had some change, so it will be necessary to test to know.

gs-ui will probably depreciate for the 2.0. For the moment, just open tickets in gs-ui-swing seems correct to me.

**Pull request merged**
