### PR TITLE
Implemented mouse over events.

### PR DESCRIPTION
**Pull request by Dave1704**
We used your tool in a research project to visualize the work of an algorithm, thanks a lot for your great work.

For our visualization, we needed mouse over events whenever the mouse is over a node for a longer time. Since it really spared us a lot of work, we'd like to donate our implementation to the project, if it is wanted.

Please feel free ask questions and suggest adjustments, to make the code fit into the project.

### CODE REVIEW

**Comment by gsavin** [comment]
Hi David,

Thanks for your request.
We are reviewing the code and we tell you once the request is accepted !

**Comment by gsavin** [comment]
We got some questions/suggestions... and you seem to be opened to discussion.

We think it can be a nice additional feature. However, we are worried about the impact of the call to `findNodeOrSpritesAt(...)` each time there is a mouse-moved event on the global performances of the viewer. Maybe it should be an other MouseManager, extending the default one, that users could use if they need this feature. What do you think ?

When adding a new task to the `Timer`, does the previous one should not be cancelled ?

Finally, maybe the delay (1000) should be a parameter of the `MouseManager`, with a negative or zero delay meaning that we do not want any delay ?

**Comment by Dave1704** [comment]
Concerning the call to `findNodeOrSpritesAt(...)`, actually for us it wasn't a problem at all, even though we had thousands of nodes. But it is just a small adjustement, so I can change it that way and you guys can test it out and compare it easily.

For the `TimerTask`s, yes they should be cancelled.

I'm also fine with the parametrized delay, it seems to be a good idea.

I'm not sure when exactly I will have the time to do these changes, but probably somewhere over the next week.

**Comment by Dave1704** [comment]
I applied the changes you proposed, everything should work now as discussed before.

**Comment by gsavin** [comment]
Thanks !

**Pull request merged**
