### PR TITLE
ui.selected attribute not set for edges #140

### PR DESCRIPTION
**Pull request by trembb01**
I was revisiting using your library and wanted to have the ability to select edges.

I generalized methods to find graphic elements by type.  I kept DefaultMouseManager's default constructor to only send methods for nodes and sprites, but allow another constructor to define which methods will be listening.  This also has a side benefit of being able to specify which graphic objects will be checked, so someone could only allow certain types to be selected.

Right now, the edge is selected if the selected area encompasses the midpoint of the edge, since this is the GraphicEdge's X and Y coordinates.  I was unsure if it would be better for the selection to require the full edge to be within the selection.  If this were the case, then the nodes would have to be selected as well.

Although I did also add code for finding an edge in the click event, it's debated if this is worthwhile since it seems difficult to click the exact midpoint of the edge w/o any visual representation.  Perhaps it would be better to test if any point of the edge was clicked.

### CODE REVIEW

**Comment by pigne** [comment]
Thanks It looks great!

Question 1:  Since your PR changes the public API (in  `View` and `Camera` interfaces), I wonder if we need to change anything in gs-ui?

Question 2: Do you think this could help fix/workaround bug #216? Or maybe it does and I didn't read your code properly...

Thanks again.

**Comment by trembb01** [comment]
Yes, I think you're right about the changes affecting gs-ui.  I changed the API on Viewer, GraphRenderer, and Camera.  The associated classes in gs-ui are org.graphstream.ui.j2dviewer.2DGraphRenderer, org.graphstream.ui.j2dviewer.Camera

So it looks like the Scala implementation will need to be updated.  This does not look like a lot of code, but I don't have Scala set up for compilation so I'll need to fork and test.  

The other approach is to not modify these public interfaces but rather add an interface for the new methods.  I think I'll take this approach.

**Comment by pigne** [comment]
Tests are passing. I'll merge this in the `master` branch as well as in branch `2.x`. But the `gs-ui` project will have to be updated accordingly.

**Comment by kenchiu21** [comment]
I found label was not showing when i try to set ui.label attribute for edge, I used FxViewPanel to do so.

Here is my CSS

> edge {  
> 	text-style:normal;  
> 	text-mode:normal;  
> 	text-background-mode:none; 
> 	text-alignment:at-left	
> }

**Pull request merged**
