### PR TITLE
Added new Http Server

### PR DESCRIPTION
**Pull request by MaSven**
As previous mentioned in #223 librarys should avoid using sun libs because this libs are not considered being stable. I Added a new Dependency and also implemented the new server with a Junit test that gives us 100% coverage. The apache Http Client is only used for the JUnit test.

### CODE REVIEW

**Comment by pigne** [comment]
Thanks for updating these old dependencies! But I see you did more than that.  I have two questions before we merge this. 

1) I like the fact that you used HTTP verbs "POST" and "DELETE" to describe the creation and deletion of nodes. I's more REST-like. But I don't see anything about nodes/edges modifications. This API used to give access to attributes addition/removal to nodes, edges and the graph itself.
Is there a reason for dropping this features knowing that any GS API will need these? 

2) You are sending html responses. Wouldn't it be more interesting to send JSON back?

**Comment by MaSven** [comment]
1. I just reimplmented that that was already there. If you have a look on the original HTTPServer only a few of the mentioned actions in the doc are implemented. Only taking steps and deleting and adding nodes are implemented. [Original](https://github.com/graphstream/gs-core/blob/2.x/src/org/graphstream/stream/net/HTTPSource.java). I can implement it if you want it.

2. I can do that. But then i want to fill the json with useful data. Right now its just operation failed or not.

**Comment by pigne** [comment]
Ok I See. In that case I will merge, but in my opinion those two points are valuable features. Maybe for another PR ;-) 

Thank you!

**Comment by MaSven** [comment]
I will definitely create another pull with these features wasn't sure about breaking things.

**Comment by pigne** [comment]
In my opinion, it is worth breaking things in that case because it allows us to have a more "restfull" kind of service, with HTTP verbs, unique URLs for each resource, and a proper response schema (in JSON) that returns more than only error (e.g. node/edge ids in case of creation...)

Looking forward for your PR.

**Pull request merged**
